// <auto-generated />
namespace BackOfficeRAM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class alteracaoassociacaouserimagem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alteracaoassociacaouserimagem));
        
        string IMigrationMetadata.Id
        {
            get { return "202005082213476_alteracao-associacao-user-imagem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
