// <auto-generated />
namespace BackOfficeRAM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mudnomeatrpt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mudnomeatrpt));
        
        string IMigrationMetadata.Id
        {
            get { return "202003271643492_mud-nome-atr-pt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
